import requests  # Import the requests library for making HTTP requests


def test_get_posts():
    # Send a GET request to the API endpoint
    res = requests.get("https://jsonplaceholder.typicode.com/posts")
    # Assert that the response status code is 200 (OK)
    assert res.status_code == 200
    # Assert that the response body is a list (of posts)
    assert isinstance(res.json(), list)


def test_create_post():
    payload = {
        "title": "Test from Pavlo",
        "body": "This post was created for testing purposes.",
        "userId": 99
    }

    res = requests.post("https://jsonplaceholder.typicode.com/posts", json=payload)

    # Check that the request was successful
    assert res.status_code == 201  # 201 Created

    # Check that the response contains our data
    data = res.json()
    assert data["title"] == payload["title"]
    assert data["body"] == payload["body"]
    assert data["userId"] == payload["userId"]
    assert "id" in data  # Fake ID generated by API
